DSNN:
  batch_norm: 1
  alpha: 0.05
  dropout: 0.025
  n_features:
    TauTrack: 14
    NeutralPFO: 22
    ShotPFO: 6
    ConvTrack: 14
  # For TDD (Phi)
  n_inputs:
    TauTrack: [30,30,20]
    NeutralPFO: [80,80,60,60]
    ShotPFO: [20,20,20]
    ConvTrack: [30,30,20]
  n_tdd:
    TauTrack: 3
    NeutralPFO: 4
    ShotPFO: 3
    ConvTrack: 3
  # for Dense (F)
  n_hiddens:
    TauTrack: [20,20,20]
    NeutralPFO: [60,40,40]
    ShotPFO: [20,20,20]
    ConvTrack: [20,20,20]
  n_h:
    TauTrack: 3
    NeutralPFO: 3
    ShotPFO: 3
    ConvTrack: 3
  n_steps:
    TauTrack: 3
    NeutralPFO: 8
    ShotPFO: 6
    ConvTrack: 4
  # FC
  n_fc1: 100
  n_fc2: 50
  n_classes: 5
