LSTM:
  name: "LSTM"
  gpus: 1
  workers: 4
  lmdb_dir: "NNAlgs/data/lmdb/decaymode/"
  gen: "DecayModePi0varGenLoader"
  model: "ModelLSTM"
  arch: "NNAlgs/config/ArchLSTM.yaml"
  epochs: 100
  patience: 10
  save_dir: "NNAlgs/saved/lstm"
  tune: "lstm_tune"
  tune_model: "ModelBuildLSTM"
  verbose: 1
  opt: "adam"