LSTM:
  name: "LSTM"
  gpus: 1
  workers: 8
  lmdb_dir: "NNAlgs/data/lmdb/decaymode/"
  gen: "DecayModePi0varGenLoader"
  model: "ModelLSTM"
  arch: "NNAlgs/config/ArchLSTM-R22.yaml"
  epochs: 100
  patience: 10
  save_dir: "NNAlgs/saved/baseline_lstm_r22_batch1k"
  tune: "lstm_tune"
  tune_model: "ModelBuildLSTM"
  verbose: 2
  opt: "adam"