DSNN:
  name: "DSNN"
  gpus: 4
  workers: 24
  lmdb_dir: "data/lmdb/decaymode/"
  gen: "DecayModePi0varTrainGenLoader"
  model: "ModelDSNN"
  arch: "config/ArchDSNN.yaml"
  epochs: 100
  patience: 10
  save_dir: "saved/dsnn"
  tune: "dsnn_tune"
  tune_model: "ModelBuildDSNN"
  verbose: 1
  opt: "adam"