DSNN:
  name: "DSNN"
  gpus: 1
  workers: 8
  lmdb_dir: "NNAlgs/data/lmdb/decaymode/"
  gen: "DecayModePi0varGenLoader"
  model: "ModelDSNN"
  arch: "NNAlgs/config/ArchDSNN-R22.yaml"
  epochs: 100
  patience: 10
  save_dir: "NNAlgs/saved/baseline_dsnn_r22/"
  tune: "dsnn_tune"
  tune_model: "ModelBuildDSNN"
  verbose: 2
  opt: "adam"