DSNN:
  name: "DSNN"
  gpus: 1
  workers: 4
  lmdb_dir: "NNAlgs/data/lmdb/decaymode/"
  gen: "DecayModePi0varGenLoader"
  model: "ModelDSNN"
  arch: "NNAlgs/config/ArchDSNN.yaml"
  epochs: 100
  patience: 10
  save_dir: "NNAlgs/saved/dsnn"
  tune: "dsnn_tune"
  tune_model: "ModelBuildDSNN"
  verbose: 1
  opt: "adam"